export const students = [
  {
    id: 1,
    fullName: "Lương Chính Quốc",
    gender: "male",
    age: 24,
    major: "CNTT",
    score: 10,
  },
  {
    id: 2,
    fullName: "Nguyễn Thị Mai",
    gender: "female",
    age: 22,
    major: "Kinh tế",
    score: 10,
  },
  {
    id: 3,
    fullName: "Trần Văn Hùng",
    gender: "male",
    age: 23,
    major: "Kỹ thuật điện",
    score: 6.5,
  },
  {
    id: 4,
    fullName: "Phạm Ngọc Anh",
    gender: "female",
    age: 21,
    major: "Sư phạm",
    score: 9.7,
  },
  {
    id: 5,
    fullName: "Lê Minh Tuấn",
    gender: "male",
    age: 25,
    major: "CNTT",
    score: 8.2,
  },
  {
    id: 6,
    fullName: "Hoàng Thị Lan",
    gender: "female",
    age: 22,
    major: "Marketing",
    score: 7.4,
  },
  {
    id: 7,
    fullName: "Đỗ Văn Nam",
    gender: "male",
    age: 24,
    major: "Cơ khí",
    score: 4.2,
  },
  {
    id: 8,
    fullName: "Vũ Thị Hồng",
    gender: "female",
    age: 23,
    major: "Y học",
    score: 9.5,
  },
  {
    id: 9,
    fullName: "Bùi Quang Vinh",
    gender: "male",
    age: 22,
    major: "Kiến trúc",
    score: 6.8,
  },
  {
    id: 10,
    fullName: "Ngô Thị Thảo",
    gender: "female",
    age: 21,
    major: "Luật",
    score: 8.6,
  },
  {
    id: 11,
    fullName: "Nguyễn Văn Cường",
    gender: "male",
    age: 23,
    major: "Toán học",
    score: 3.5,
  },
  {
    id: 12,
    fullName: "Trần Thị Kim",
    gender: "female",
    age: 22,
    major: "Văn học",
    score: 1.8,
  },
  {
    id: 13,
    fullName: "Phan Hoàng Sơn",
    gender: "male",
    age: 24,
    major: "CNTT",
    score: 9.2,
  },
];
